# Numpy
arrays. Tienen que ser datos homogeneos, si la matriz es de enteros, no se puede poner un float

In [75]:
import numpy as np

In [4]:
L1 = [1,2,3,4,5,6,7,8]#Crear una lista

In [6]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
x1 = np.array(L1, dtype = 'float32')
x1

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.arange(4,5.1,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

In [13]:
np.linspace(1,7,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.ravel(x)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [18]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
x.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [20]:
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Propiedades de los arrays

In [23]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
x.ndim

2

In [28]:
x.shape

(3, 4)

In [29]:
x.size

12

In [30]:
x[2]

array([ 8,  9, 10, 11])

In [31]:
x[2,3]

11

In [32]:
x[0]

array([0, 1, 2, 3])

In [34]:
x[2]

array([ 8,  9, 10, 11])

In [35]:
x[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [37]:
x[0:3,0]

array([0, 4, 8])

In [38]:
x[x<5]

array([0, 1, 2, 3, 4])

In [39]:
cond = x < 3
cond

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [40]:
x[cond]

array([0, 1, 2])

In [41]:
x[1:3] = 999

In [42]:
x

array([[  0,   1,   2,   3],
       [999, 999, 999, 999],
       [999, 999, 999, 999]])

In [43]:
x

array([[  0,   1,   2,   3],
       [999, 999, 999, 999],
       [999, 999, 999, 999]])

In [44]:
x[1]=3.444444

In [46]:
x

array([[  0,   1,   2,   3],
       [  3,   3,   3,   3],
       [999, 999, 999, 999]])

In [47]:
1.2j

1.2j

In [48]:
9+1j

(9+1j)

# copias y vistas de arrays

In [50]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
y = x

In [56]:
y.shape = (3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
x is y

True

In [54]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
z = x.copy()

In [59]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
z is x

False

In [61]:
t = x.view()
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
t is x

False

In [64]:
t.shape = (6,2)
t

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [65]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
t[0] = 9999

In [67]:
t

array([[9999, 9999],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9],
       [  10,   11]])

In [68]:
x

array([[9999, 9999,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

# Funciones universales (ufunc)

+ Unarias: sqrt, sin, cos, etc
+ Binarias: maximum, minimum, etc

In [78]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [77]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [80]:
np.sum(x)

45

In [89]:
x.sum()

45

In [81]:
np.nansum(x)

45

In [82]:
np.mean(x)

4.5

In [83]:
np.min(x)

0

In [84]:
np.std(x)

2.8722813232690143

In [102]:
np.random.seed(123)
z = np.random.random((3,5))

In [103]:
z

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426]])

In [90]:
z.sum(axis=0)

array([2.21914469, 1.501249  , 2.7376827 , 1.06078546, 1.57017118])

In [91]:
z.sum(axis=1)

array([2.69216085, 2.68779897, 3.70907321])